//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLURUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLURUNLER()
        {
            this.TBLSATISLAR = new HashSet<TBLSATISLAR>();
        }
    
        public int URUNID { get; set; }
        [Required(ErrorMessage ="Bu alaný boþ geçemezsiniz.")]
        [StringLength(40,ErrorMessage ="En fazla 40 karakter girebilirsiniz.")]
        public string URUNAD { get; set; }
        [Required(ErrorMessage = "Bu alaný boþ geçemezsiniz.")]
        [StringLength(25, ErrorMessage = "En fazla 25 karakter girebilirsiniz.")]
        public string MARKA { get; set; }
        [Required(ErrorMessage = "Bu alaný boþ geçemezsiniz.")]
        [StringLength(40, ErrorMessage = "En fazla 40 karakter girebilirsiniz.")]
        public Nullable<short> URUNKATEGORI { get; set; }
        [Required(ErrorMessage = "Bu alaný boþ geçemezsiniz.")]
        public Nullable<decimal> FIYAT { get; set; }
        [Required(ErrorMessage = "Bu alaný boþ geçemezsiniz.")]
        public Nullable<byte> STOK { get; set; }
    
        public virtual TBLKATEGORILER TBLKATEGORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATISLAR> TBLSATISLAR { get; set; }
    }
}
